#!/usr/bin/env python3
"""Validate, aggregate, and report the UmoWeb six-field access log."""

from __future__ import annotations

import argparse
import gzip
import html
import ipaddress
import json
import os
import re
import sys
import tempfile
from collections import Counter, defaultdict
from datetime import date, datetime, time, timedelta, timezone
from pathlib import Path
from typing import Iterable, Mapping


LOG_FIELDS = frozenset({"time", "ip", "method", "path", "status", "bytes"})
LOG_FILE_PATTERN = re.compile(r"^access-(\d{8}T\d{6}Z)\.log(?:\.gz)?$")
AGGREGATE_FILE_PATTERN = re.compile(r"^\d{4}-\d{2}-\d{2}\.json$")
METHOD_PATTERN = re.compile(r"^[A-Z]{3,10}$")

DEFAULT_CONFIG = {
    "ACCESS_LOG_DIR": "/opt/umoweb/access/logs",
    "ACCESS_AGGREGATE_DIR": "/opt/umoweb/access/aggregates",
    "ACCESS_REPORT_DIR": "/opt/umoweb/access/reports",
    "ACCESS_RAW_RETENTION_DAYS": "30",
    "ACCESS_AGGREGATE_RETENTION_DAYS": "180",
    "ACCESS_REPORT_HOST": "127.0.0.1",
    "ACCESS_REPORT_PORT": "7890",
    "ACCESS_TRUSTED_PROXIES": "",
    "COMPOSE_FILE": "/opt/umoweb/compose.yaml",
    "COMPOSE_ENV_FILE": "/opt/umoweb/.env.docker",
    "COMPOSE_PROJECT": "umoweb",
}

ALLOWED_CONFIG_KEYS = frozenset(DEFAULT_CONFIG)


def _parse_positive_int(value: object, name: str, minimum: int, maximum: int) -> int:
    if isinstance(value, bool):
        raise ValueError(f"{name} must be an integer")
    try:
        parsed = int(str(value))
    except (TypeError, ValueError) as error:
        raise ValueError(f"{name} must be an integer") from error
    if parsed < minimum or parsed > maximum:
        raise ValueError(f"{name} must be between {minimum} and {maximum}")
    return parsed


def read_env_file(path: os.PathLike[str] | str) -> dict[str, str]:
    values: dict[str, str] = {}
    with open(path, "r", encoding="utf-8") as handle:
        for line_number, raw_line in enumerate(handle, start=1):
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                raise ValueError(f"invalid config line {line_number}: missing '='")
            key, value = line.split("=", 1)
            key = key.strip()
            if key not in ALLOWED_CONFIG_KEYS:
                raise ValueError(f"unsupported access config key: {key}")
            values[key] = value.strip()
    return values


def load_config(path: os.PathLike[str] | str) -> dict[str, object]:
    values = dict(DEFAULT_CONFIG)
    values.update(read_env_file(path))
    config: dict[str, object] = {
        "log_dir": values["ACCESS_LOG_DIR"],
        "aggregate_dir": values["ACCESS_AGGREGATE_DIR"],
        "report_dir": values["ACCESS_REPORT_DIR"],
        "raw_retention_days": _parse_positive_int(
            values["ACCESS_RAW_RETENTION_DAYS"],
            "ACCESS_RAW_RETENTION_DAYS",
            7,
            30,
        ),
        "aggregate_retention_days": _parse_positive_int(
            values["ACCESS_AGGREGATE_RETENTION_DAYS"],
            "ACCESS_AGGREGATE_RETENTION_DAYS",
            1,
            3650,
        ),
        "report_host": str(values["ACCESS_REPORT_HOST"]).strip(),
        "report_port": _parse_positive_int(
            values["ACCESS_REPORT_PORT"],
            "ACCESS_REPORT_PORT",
            1,
            65535,
        ),
        "trusted_proxies": str(values["ACCESS_TRUSTED_PROXIES"]).strip(),
    }
    for key in ("log_dir", "aggregate_dir", "report_dir"):
        if not str(config[key]).strip():
            raise ValueError(f"{key} must not be empty")
    if not config["report_host"]:
        raise ValueError("ACCESS_REPORT_HOST must not be empty")
    return config


def render_trusted_proxies(config: Mapping[str, object]) -> str:
    value = str(config.get("trusted_proxies", "")).strip()
    lines = [
        "# Generated by scripts/access/install-access-timer.sh; do not edit.",
        "real_ip_header X-Forwarded-For;",
        "real_ip_recursive on;",
    ]
    if not value:
        return "\n".join(lines) + "\n"

    for raw_entry in value.split(","):
        entry = raw_entry.strip()
        if not entry:
            continue
        try:
            ipaddress.ip_network(entry, strict=False)
        except ValueError as error:
            raise ValueError(f"invalid trusted proxy network: {entry}") from error
        lines.append(f"set_real_ip_from {entry};")
    return "\n".join(lines) + "\n"


def render_privacy_config(config: Mapping[str, object]) -> str:
    payload = {
        "rawRetentionDays": int(config["raw_retention_days"]),
        "aggregateRetentionDays": int(config["aggregate_retention_days"]),
    }
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + "\n"


def _atomic_write(path: os.PathLike[str] | str, content: str, mode: int) -> None:
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    file_descriptor, temporary_name = tempfile.mkstemp(
        dir=destination.parent,
        prefix=f".{destination.name}.",
        text=True,
    )
    try:
        with os.fdopen(file_descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary_name, mode)
        os.replace(temporary_name, destination)
    except Exception:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise


def parse_access_log_line(line: str) -> dict[str, object]:
    try:
        payload = json.loads(line)
    except json.JSONDecodeError as error:
        raise ValueError("access log line is not valid JSON") from error
    if not isinstance(payload, dict) or set(payload) != LOG_FIELDS:
        raise ValueError("access log line must contain exactly six fields")

    raw_time = payload["time"]
    if not isinstance(raw_time, str):
        raise ValueError("access log time must be a string")
    try:
        parsed_time = datetime.fromisoformat(raw_time.replace("Z", "+00:00"))
    except ValueError as error:
        raise ValueError("access log time must be ISO 8601") from error
    if parsed_time.tzinfo is None:
        raise ValueError("access log time must include a timezone")

    raw_ip = payload["ip"]
    if not isinstance(raw_ip, str):
        raise ValueError("access log IP must be a string")
    try:
        ipaddress.ip_address(raw_ip)
    except ValueError as error:
        raise ValueError("access log IP is invalid") from error

    method = payload["method"]
    if not isinstance(method, str) or not METHOD_PATTERN.fullmatch(method):
        raise ValueError("access log method is invalid")

    path = payload["path"]
    if (
        not isinstance(path, str)
        or not path.startswith("/")
        or "?" in path
        or "#" in path
        or any(ord(character) < 32 for character in path)
        or len(path) > 2048
    ):
        raise ValueError("access log path must be a query-free URI path")

    status = payload["status"]
    if isinstance(status, bool) or not isinstance(status, int) or not 100 <= status <= 599:
        raise ValueError("access log status is invalid")

    bytes_sent = payload["bytes"]
    if isinstance(bytes_sent, bool) or not isinstance(bytes_sent, int) or bytes_sent < 0:
        raise ValueError("access log byte count is invalid")

    return {
        "time": parsed_time,
        "ip": str(ipaddress.ip_address(raw_ip)),
        "method": method,
        "path": path,
        "status": status,
        "bytes": bytes_sent,
    }


def _read_log_file(path: Path) -> tuple[list[dict[str, object]], int]:
    records: list[dict[str, object]] = []
    invalid = 0
    opener = gzip.open if path.suffix == ".gz" else open
    with opener(path, "rt", encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not line:
                continue
            try:
                records.append(parse_access_log_line(line))
            except ValueError:
                invalid += 1
    return records, invalid


def collect_records(log_dir: os.PathLike[str] | str) -> tuple[list[dict[str, object]], int]:
    records: list[dict[str, object]] = []
    invalid = 0
    directory = Path(log_dir)
    if not directory.exists():
        return records, invalid

    paths = sorted(
        path
        for path in directory.iterdir()
        if path.is_file() and (path.name == "access.log" or LOG_FILE_PATTERN.fullmatch(path.name))
    )
    for path in paths:
        file_records, file_invalid = _read_log_file(path)
        records.extend(file_records)
        invalid += file_invalid
    return records, invalid


def aggregate_records(records: Iterable[Mapping[str, object]]) -> dict[str, dict[str, object]]:
    grouped: dict[str, dict[str, object]] = {}
    for record in records:
        record_time = record["time"]
        if isinstance(record_time, str):
            record_time = datetime.fromisoformat(record_time.replace("Z", "+00:00"))
        record_date = record_time.date().isoformat()
        aggregate = grouped.setdefault(
            record_date,
            {
                "date": record_date,
                "requestCount": 0,
                "uniqueIpCount": 0,
                "responseBytes": 0,
                "statuses": Counter(),
                "methods": Counter(),
                "paths": Counter(),
                "ips": set(),
                "invalidLineCount": 0,
            },
        )
        aggregate["requestCount"] += 1
        aggregate["responseBytes"] += int(record["bytes"])
        aggregate["statuses"][str(record["status"])] += 1
        aggregate["methods"][str(record["method"])] += 1
        aggregate["paths"][str(record["path"])] += 1
        aggregate["ips"].add(str(record["ip"]))

    result: dict[str, dict[str, object]] = {}
    for record_date, aggregate in grouped.items():
        top_paths = [
            {"path": path, "count": count}
            for path, count in sorted(
                aggregate["paths"].items(),
                key=lambda item: (-item[1], item[0]),
            )[:100]
        ]
        result[record_date] = {
            "schemaVersion": 1,
            "date": record_date,
            "requestCount": aggregate["requestCount"],
            "uniqueIpCount": len(aggregate["ips"]),
            "responseBytes": aggregate["responseBytes"],
            "statuses": dict(sorted(aggregate["statuses"].items())),
            "methods": dict(sorted(aggregate["methods"].items())),
            "topPaths": top_paths,
            "invalidLineCount": aggregate["invalidLineCount"],
        }
    return dict(sorted(result.items()))


def _raw_file_timestamp(path: Path) -> datetime | None:
    match = LOG_FILE_PATTERN.fullmatch(path.name)
    if not match:
        return None
    return datetime.strptime(match.group(1), "%Y%m%dT%H%M%SZ").replace(tzinfo=timezone.utc)


def prune_raw_files(log_dir: os.PathLike[str] | str, now: datetime, retention_days: int) -> int:
    directory = Path(log_dir)
    if not directory.exists():
        return 0
    removed = 0
    cutoff = now.astimezone(timezone.utc) - timedelta(days=retention_days)
    for path in directory.iterdir():
        timestamp = _raw_file_timestamp(path)
        if timestamp is None or timestamp >= cutoff:
            continue
        path.unlink()
        removed += 1
    return removed


def _aggregate_file_date(path: Path) -> date | None:
    if not AGGREGATE_FILE_PATTERN.fullmatch(path.name):
        return None
    try:
        return date.fromisoformat(path.stem)
    except ValueError:
        return None


def prune_aggregate_files(
    aggregate_dir: os.PathLike[str] | str,
    now: datetime,
    retention_days: int,
) -> int:
    directory = Path(aggregate_dir)
    if not directory.exists():
        return 0
    removed = 0
    cutoff = now.astimezone(timezone.utc) - timedelta(days=retention_days)
    for path in directory.iterdir():
        file_date = _aggregate_file_date(path)
        if file_date is None:
            continue
        file_timestamp = datetime.combine(file_date, time(23, 59, 59), tzinfo=timezone.utc)
        if file_timestamp >= cutoff:
            continue
        path.unlink()
        removed += 1
    return removed


def _format_bytes(value: int) -> str:
    units = ("B", "KiB", "MiB", "GiB", "TiB")
    amount = float(value)
    for unit in units:
        if amount < 1024 or unit == units[-1]:
            if unit == "B":
                return f"{int(amount)} {unit}"
            return f"{amount:.1f} {unit}"
        amount /= 1024
    return f"{value} B"


def render_report(
    records: Iterable[Mapping[str, object]],
    aggregates: Mapping[str, Mapping[str, object]],
    generated_at: datetime,
) -> str:
    record_list = list(records)
    status_counts = Counter(str(record["status"]) for record in record_list)
    path_counts = Counter(str(record["path"]) for record in record_list)
    ip_counts = Counter(str(record["ip"]) for record in record_list)
    total_bytes = sum(int(record["bytes"]) for record in record_list)
    unique_ips = len(ip_counts)

    def rows(counter: Counter[str], label: str) -> str:
        if not counter:
            return f"<tr><td colspan=\"2\">暂无{html.escape(label)}</td></tr>"
        return "".join(
            f"<tr><td>{html.escape(value)}</td><td>{count}</td></tr>"
            for value, count in sorted(counter.items(), key=lambda item: (-item[1], item[0]))[:20]
        )

    daily_rows = "".join(
        "<tr>"
        f"<td>{html.escape(record_date)}</td>"
        f"<td>{int(aggregate['requestCount'])}</td>"
        f"<td>{int(aggregate['uniqueIpCount'])}</td>"
        f"<td>{html.escape(_format_bytes(int(aggregate['responseBytes'])))}</td>"
        "</tr>"
        for record_date, aggregate in sorted(aggregates.items())
    )
    if not daily_rows:
        daily_rows = '<tr><td colspan="4">暂无聚合数据</td></tr>'

    generated = generated_at.astimezone(timezone.utc).replace(microsecond=0).isoformat().replace(
        "+00:00",
        "Z",
    )
    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="robots" content="noindex,nofollow">
  <title>UmoWeb 短期访问安全报表</title>
  <style>
    :root {{ color-scheme: light; font-family: system-ui, sans-serif; background: #f4efe4; color: #2d241b; }}
    body {{ width: min(1120px, calc(100% - 32px)); margin: 0 auto; padding: 32px 0 64px; }}
    h1, h2 {{ font-family: Georgia, serif; font-weight: 500; }}
    header {{ border-bottom: 2px solid #6f5136; margin-bottom: 24px; }}
    .summary {{ display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 12px; }}
    .summary article, section {{ border: 1px solid #b9a98f; background: #fffaf0; padding: 18px; }}
    .summary strong {{ display: block; font-size: 24px; }}
    .grid {{ display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 18px; margin-top: 18px; }}
    table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
    th, td {{ border-bottom: 1px solid #d9cdb9; padding: 7px 8px; text-align: left; overflow-wrap: anywhere; }}
    th:last-child, td:last-child {{ text-align: right; }}
    @media (max-width: 760px) {{
      .summary, .grid {{ grid-template-columns: 1fr; }}
    }}
  </style>
</head>
<body>
  <header>
    <p>UmoWeb / Security Operations</p>
    <h1>短期访问安全报表</h1>
    <p>生成时间：{html.escape(generated)}；数据仅覆盖当前未过期的原始访问日志。</p>
  </header>
  <div class="summary">
    <article><span>请求总数</span><strong>{len(record_list)}</strong></article>
    <article><span>独立 IP</span><strong>{unique_ips}</strong></article>
    <article><span>响应字节</span><strong>{html.escape(_format_bytes(total_bytes))}</strong></article>
    <article><span>4xx / 5xx</span><strong>{sum(count for code, count in status_counts.items() if code.startswith(('4', '5')))}</strong></article>
  </div>
  <div class="grid">
    <section><h2>客户端 IP</h2><table><tbody>{rows(ip_counts, "IP")}</tbody></table></section>
    <section><h2>访问路径</h2><table><tbody>{rows(path_counts, "路径")}</tbody></table></section>
    <section><h2>状态码</h2><table><tbody>{rows(status_counts, "状态码")}</tbody></table></section>
    <section><h2>每日聚合</h2><table><thead><tr><th>日期</th><th>请求</th><th>IP</th><th>字节</th></tr></thead><tbody>{daily_rows}</tbody></table></section>
  </div>
</body>
</html>
"""


def run_maintenance(config: Mapping[str, object], now: datetime) -> dict[str, int]:
    log_dir = Path(str(config["log_dir"]))
    aggregate_dir = Path(str(config["aggregate_dir"]))
    report_dir = Path(str(config["report_dir"]))
    raw_retention_days = int(config["raw_retention_days"])
    aggregate_retention_days = int(config["aggregate_retention_days"])

    for directory in (log_dir, aggregate_dir, report_dir):
        directory.mkdir(parents=True, exist_ok=True)

    removed_raw = prune_raw_files(log_dir, now, raw_retention_days)
    records, invalid = collect_records(log_dir)
    aggregates = aggregate_records(records)

    for record_date, aggregate in aggregates.items():
        _atomic_write(
            aggregate_dir / f"{record_date}.json",
            json.dumps(aggregate, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            0o640,
        )
    removed_aggregates = prune_aggregate_files(
        aggregate_dir,
        now,
        aggregate_retention_days,
    )
    report = render_report(records, aggregates, now)
    _atomic_write(report_dir / "index.html", report, 0o640)

    return {
        "records": len(records),
        "invalid": invalid,
        "removedRawFiles": removed_raw,
        "removedAggregateFiles": removed_aggregates,
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    render = subparsers.add_parser("render-config")
    render.add_argument("--config", required=True)
    render.add_argument("--privacy-output", required=True)
    render.add_argument("--trusted-output", required=True)

    run = subparsers.add_parser("run")
    run.add_argument("--config", required=True)
    run.add_argument("--now", help="ISO 8601 UTC timestamp used for retention tests")
    return parser


def main(argv: list[str] | None = None) -> int:
    arguments = build_parser().parse_args(argv)
    config = load_config(arguments.config)

    if arguments.command == "render-config":
        _atomic_write(arguments.privacy_output, render_privacy_config(config), 0o644)
        _atomic_write(arguments.trusted_output, render_trusted_proxies(config), 0o644)
        return 0

    now = datetime.now(timezone.utc)
    if arguments.now:
        now = datetime.fromisoformat(arguments.now.replace("Z", "+00:00"))
        if now.tzinfo is None:
            raise ValueError("--now must include a timezone")
    result = run_maintenance(config, now)
    json.dump(result, sys.stdout, ensure_ascii=False, sort_keys=True)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
