import client from './client'

export const login           = (data) => client.post('/admin/login', data)
export const changePassword  = (data) => client.put('/admin/change-password', data)
export const getAdminContents= (p)    => client.get('/admin/contents', { params: p })
export const getAdminContent = (id)   => client.get(`/admin/contents/${id}`)
export const createContent   = (data) => client.post('/admin/contents', data)
export const updateContent   = (id,d) => client.put(`/admin/contents/${id}`, d)
export const bulkUpdateContents = (data) => client.post('/admin/contents/bulk', data)
export const deleteContent   = (id)   => client.delete(`/admin/contents/${id}`)
export const getAdminCats    = (type) => client.get('/admin/categories', { params: type ? { type } : {} })
export const getAdminCat     = (id)   => client.get(`/admin/categories/${id}`)
export const createCategory  = (data) => client.post('/admin/categories', data)
export const updateCategory  = (id,d) => client.put(`/admin/categories/${id}`, d)
export const deleteCategory  = (id)   => client.delete(`/admin/categories/${id}`)
export const listAdminTags   = ()     => client.get('/admin/tags')
export const createTag       = (data) => client.post('/admin/tags', data)
export const updateTag       = (id,d) => client.put(`/admin/tags/${id}`, d)
export const deleteTag       = (id)   => client.delete(`/admin/tags/${id}`)
export const uploadImage     = (file) => { const fd = new FormData(); fd.append('file', file); return client.post('/admin/images/upload', fd) }
export const getAdminImages  = (p)    => client.get('/admin/images', { params: p })
export const getImageIntegrity = ()   => client.get('/admin/images/integrity')
export const deleteImage     = (id)   => client.delete(`/admin/images/${id}`)
export const getOptions      = ()     => client.get('/admin/options')
export const updateOption    = (k,v)  => client.put(`/admin/options/${k}`, { value: v })
export const getAiModes      = ()     => client.get('/admin/ai/modes')
export const createAiMode    = (data) => client.post('/admin/ai/modes', data)
export const copyAiMode      = (id,d) => client.post(`/admin/ai/modes/${id}/copy`, d)
export const updateAiMode    = (id,d) => client.put(`/admin/ai/modes/${id}`, d)
export const getAiModeVersions = (id) => client.get(`/admin/ai/modes/${id}/versions`)
export const rollbackAiMode  = (id,versionNo,expectedVersion) => (
  client.post(`/admin/ai/modes/${id}/rollback/${versionNo}`, { expectedVersion })
)
export const getAiCapabilities = () => client.get('/admin/ai/capabilities')
export const transformAiContent = (data, config = {}) => (
  client.post('/admin/ai/transform', data, config)
)
